### ISSUE TITLE
SyntaxError: invalid syntax: compress = FlaskStaticCompress(app)io = SocketIO()

### ISSUE THREAD

**Issue by kevinp2** [italomaia/flask-empty#40]
I am trying out this cookiecutter, being completely new to it.

Upon running: make run-dev I get this error message:

```
SyntaxError
File "/Repositories/WebApps/flasktest2/extensions.py", line 33
    compress = FlaskStaticCompress(app)io = SocketIO()
                                       ^
SyntaxError: invalid syntax

Traceback (most recent call last)
File "/Repositories/WebApps/flasktest2/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/Repositories/WebApps/flasktest2/wsgi.py", line 13, in <module>
app = app_factory(config_obj_path, project_name)
File "/Repositories/WebApps/flasktest2/main.py", line 54, in app_factory
app.setup()
File "/Repositories/WebApps/flasktest2/venv/lib/python3.9/site-packages/empty/app.py", line 114, in setup
self.configure_extensions()
File "/Repositories/WebApps/flasktest2/venv/lib/python3.9/site-packages/empty/app.py", line 205, in configure_extensions
ext = import_string(ext_path)
File "/Repositories/WebApps/flasktest2/venv/lib/python3.9/site-packages/werkzeug/utils.py", line 568, in import_string
__import__(import_name)
File "/Repositories/WebApps/flasktest2/extensions.py", line 33
    compress = FlaskStaticCompress(app)io = SocketIO()
                                       ^
SyntaxError: invalid syntax
```

**Comment by italomaia** [comment]
Should be fine now. Care to give it another try?

**Comment by italomaia** [comment]
Oh well, open ticket again if problem is not solved.
